const projects = [
  {
    id: 19,
    title: "Sienna - Single Cover",
    year: "2021",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "https://open.spotify.com/album/7IP7AWnX1yQ0hqB4ENe4Ks",
    linkText: "Spotify",
    linkType: "href",
    secondaryLinkURL: "https://photos.app.goo.gl/s2itZtJm2QGd8F7t7",
    secondaryLinkText: "Instagram Story Ad (Video)",
    secondaryLinkType: "sienna_mp4",
    category: "Album Art",
    tags: ["Photoshop", "After Effects", "Album Art", "Personal Project"],
    images: [require("./portfolio_data/19_sienna_single_cover/0.jpg")],
  },
  {
    id: 18,
    title: "Fantasy Meets Reality",
    year: "2021",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Photoshop",
    tags: ["Photoshop", "Personal Project"],
    images: [
      require("./portfolio_data/18_fantasy_meets_reality/0.jpg"),
      require("./portfolio_data/18_fantasy_meets_reality/1.jpg"),
      require("./portfolio_data/18_fantasy_meets_reality/2.jpg"),
      require("./portfolio_data/18_fantasy_meets_reality/3.jpg"),
    ],
  },
  {
    id: 17,
    title: "LA Metro Rebrand",
    year: "2021",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "metro_pdf",
    linkText: "Full Project (PDF)",
    linkType: "metro_pdf",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Branding",
    tags: [
      "Illustrator",
      "Branding",
      "Social Design",
      "DES 302",
      "Design Course",
    ],
    images: [
      require("./portfolio_data/17_la_metro_rebrand/0.jpg"),
      require("./portfolio_data/17_la_metro_rebrand/1.jpg"),
      require("./portfolio_data/17_la_metro_rebrand/2.jpg"),
      require("./portfolio_data/17_la_metro_rebrand/3.jpg"),
      require("./portfolio_data/17_la_metro_rebrand/4.jpg"),
    ],
  },
  {
    id: 16,
    title: "Root's Resturant COVID-19 Line",
    year: "2021",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "roots_pdf",
    linkText: "Full Project (PDF)",
    linkType: "roots_pdf",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Branding",
    tags: [
      "Illustrator",
      "Branding",
      "Social Design",
      "DES 302",
      "Design Course",
    ],
    images: [
      require("./portfolio_data/16_roots_line/0.jpg"),
      require("./portfolio_data/16_roots_line/1.jpg"),
      require("./portfolio_data/16_roots_line/2.jpg"),
      require("./portfolio_data/16_roots_line/3.jpg"),
    ],
  },
  {
    id: 15,
    title: "Center Earth - Fashion Brand",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "ce_lookbook_pdf",
    linkText: "F/W 2020 Lookbook (PDF)",
    linkType: "ce_lookbook_pdf",
    secondaryLinkURL: "ce_project_pdf",
    secondaryLinkText: "Project Presentation (PDF)",
    secondaryLinkType: "ce_project_pdf",
    category: "Fashion Design",
    tags: [
      "Illustrator",
      "Photoshop",
      "Fashion Design",
      "DES 313",
      "Design Course",
    ],
    images: [
      require("./portfolio_data/15_center_earth/0.jpg"),
      require("./portfolio_data/15_center_earth/1.jpg"),
    ],
  },
  {
    id: 14,
    title: "Anna Sui Rebrand",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "as_project_pdf",
    linkText: "Full Project (PDF)",
    linkType: "as_project_pdf",
    secondaryLinkURL: "as_instagram_mp4",
    secondaryLinkText: "Instagram Ad (Video)",
    secondaryLinkType: "as_instagram_mp4",
    category: "Fashion Design",
    tags: [
      "Illustrator",
      "Photoshop",
      "Fashion Design",
      "DES 313",
      "Design Course",
    ],
    images: [
      require("./portfolio_data/14_anna_sui/0.jpg"),
      require("./portfolio_data/14_anna_sui/1.jpg"),
    ],
  },
  {
    id: 13,
    title: "Learn To Code",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "https://learntocode.zachizzard.com",
    linkText: "learntocode.zachizzard.com",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Web Design",
    tags: ["Front-End Development", "DES 202", "Design Course"],
    images: [
      require("./portfolio_data/13_learn_to_code/0.jpg"),
      require("./portfolio_data/13_learn_to_code/1.jpg"),
      require("./portfolio_data/13_learn_to_code/2.jpg"),
    ],
  },
  {
    id: 12,
    title: "2020 Voting Posters",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Poster Design",
    tags: [
      "Photoshop",
      "Social Design",
      "Poster Design",
      "DES 202",
      "Design Course",
    ],
    images: [
      require("./portfolio_data/12_2020_vote/0.jpg"),
      require("./portfolio_data/12_2020_vote/1.jpg"),
    ],
  },
  {
    id: 11,
    title: "Emma's Movie Cafe",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Branding",
    tags: ["Illustrator", "Branding", "DES 202", "Design Course"],
    images: [
      require("./portfolio_data/11_emma_movie_cafe/0.jpg"),
      require("./portfolio_data/11_emma_movie_cafe/1.jpg"),
    ],
  },
  {
    id: 10,
    title: "Number Set Design",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Typography",
    tags: ["Illustrator", "Typography", "DES 332B", "Design Course"],
    images: [
      require("./portfolio_data/10_number_set/0.jpg"),
      require("./portfolio_data/10_number_set/1.jpg"),
      require("./portfolio_data/10_number_set/2.jpg"),
      require("./portfolio_data/10_number_set/3.jpg"),
      require("./portfolio_data/10_number_set/4.jpg"),
    ],
  },
  {
    id: 9,
    title: "Attorney-Client Privilege Database",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "https://github.com/shreyahavaldar/ATClipper",
    linkText: "GitHub Repository",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Full-Stack Development",
    tags: [
      "Front-End Development",
      "Back-End Development",
      "CSCI 401",
      "Computer Science Course",
    ],
    images: [
      require("./portfolio_data/9_atclipper/0.jpg"),
      require("./portfolio_data/9_atclipper/1.jpg"),
    ],
  },
  {
    id: 8,
    title: "Spotify Stats",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "https://spotify.zachizzard.com",
    linkText: "spotify.zachizzard.com",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Full-Stack Development",
    tags: ["Front-End Development", "Back-End Development", "Personal Project"],
    images: [
      require("./portfolio_data/8_spotify/0.jpg"),
      require("./portfolio_data/8_spotify/1.jpg"),
    ],
  },
  {
    id: 7,
    title: "Tempo - Smino Cover Content",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Album Art",
    tags: ["Photoshop", "Album Art", "Personal Project"],
    images: [require("./portfolio_data/7_tempo/0.jpg")],
  },
  {
    id: 6,
    title: "AAAI Club Posters",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Poster Design",
    tags: ["Photoshop", "Poster Design", "Personal Project"],
    images: [
      require("./portfolio_data/6_aaai/0.jpg"),
      require("./portfolio_data/6_aaai/1.jpg"),
    ],
  },
  {
    id: 5,
    title: "Starstruck - Album Cover",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Album Art",
    tags: [
      "Illustrator",
      "Photoshop",
      "Album Art",
      "DES 332A",
      "Design Course",
    ],
    images: [require("./portfolio_data/5_starstruck/0.jpg")],
  },
  {
    id: 4,
    title: "Microbe Typeface",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "microbe_otf",
    linkText: "Font Download (OTF)",
    linkType: "microbe_otf",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Typography",
    tags: ["Illustrator", "Typography", "DES 332A", "Design Course"],
    images: [require("./portfolio_data/4_microbe/0.jpg")],
  },
  {
    id: 3,
    title: "Piecework Project",
    year: "2020",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Physical Design",
    tags: ["Physical Design", "DES 102", "Design Course"],
    images: [
      require("./portfolio_data/3_piecework/0.jpg"),
      require("./portfolio_data/3_piecework/1.jpg"),
      require("./portfolio_data/3_piecework/2.jpg"),
    ],
  },
  {
    id: 2,
    title: "Summer Film Series",
    year: "2019",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "",
    linkText: "",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Photography",
    tags: ["Photography", "Personal Project"],
    images: [
      require("./portfolio_data/2_summer_film/0.jpg"),
      require("./portfolio_data/2_summer_film/1.jpg"),
      require("./portfolio_data/2_summer_film/2.jpg"),
      require("./portfolio_data/2_summer_film/3.jpg"),
      require("./portfolio_data/2_summer_film/4.jpg"),
      require("./portfolio_data/2_summer_film/5.jpg"),
      require("./portfolio_data/2_summer_film/6.jpg"),
    ],
  },
  {
    id: 1,
    title: "Perigo",
    year: "2018",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "https://github.com/hariria/perigo",
    linkText: "GitHub Repository",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Full-Stack Development",
    tags: [
      "Front-End Development",
      "Back-End Development",
      "CSCI 201",
      "Computer Science Course",
    ],
    images: [
      require("./portfolio_data/1_perigo/0.jpg"),
      require("./portfolio_data/1_perigo/1.jpg"),
    ],
  },
  {
    id: 0,
    title: "Bitmark Node App",
    year: "2018",
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam diam lacus, mollis vel felis a, suscipit tempus justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam pellentesque in lacus eu hendrerit. Vestibulum efficitur neque lectus, vel ornare velit tincidunt non. Quisque non ex massa. Sed rutrum nec sapien ac bibendum. Curabitur cursus pulvinar rhoncus. Nam porttitor metus ut mattis pulvinar. Sed tempor sapien ac mi pulvinar blandit at sit.",
    linkURL: "https://github.com/bitmark-inc/bitmark-node-app",
    linkText: "GitHub Repository",
    linkType: "href",
    secondaryLinkURL: "",
    secondaryLinkText: "",
    secondaryLinkType: "href",
    category: "Full-Stack Development",
    tags: ["Front-End Development", "Back-End Development", "Internship"],
    images: [require("./portfolio_data/0_bitmark_node/0.jpg")],
  },
];

export default projects;
